### ISSUE TITLE
Showcase company logos in a better way

### ISSUE THREAD

**Issue by niraj8** [styled-components/styled-components-website#725]
The homepage showcases logos for companies that use styled-components in their websites with an animation

There are 70+ logos that run across the screen, below is a link to the original issue by @jfhector that explains why this is not ideal.

https://github.com/styled-components/styled-components/issues/3278

Let's discuss how can we better showcase these logos on the homepage

**Comment by jfhector** [comment]
Thanks @niraj8 .

### To meet the web content accessibility guidelines 2.1 level AA

You'd need to:
  - either not animate this thing automatically
  - or make it easy for people to stop the animation.

Here's the [relevant success criterion, with more guidance](https://www.w3.org/TR/WCAG21/#pause-stop-hide).

### To avoid people with vestibular disorders feel sick

The minimum you need to do is disable the animation within `@media (prefers-reduced-motion) { ... }`.

For example:

```css
.animation {
  animation: <your animation as it currently is>
}

/* Tone down the animation to avoid vestibular motion triggers like scaling or panning large objects. */
@media (prefers-reduced-motion) {
  .animation {
    animation-name: none;
  }
}
```

#### More details about why animations like this make people sick

‘Vestibular disorder’ is like car sickness, but triggered by motions on a screen that your brain does not expect.
Even mild parallax effects can trigger that.

I’m mildly sensitive to ‘vestibular disorder’ triggers. I feel mildly car sick a little bit sick after looking at this for a few seconds. But [other people really do feel quite sick when seeing animations like this](https://alistapart.com/article/accessibility-for-vestibular/). Here’s [another example](http://reverttosaved.com/2018/10/16/trying-to-explain-reduce-motion-to-designers-who-dont-have-a-vestibular-disorder/).

#### More guidance on `@media (prefers-reduced-motion) { ... }`

Operating systems let users say that they prefer ‘reduced motion’. Then, it’s a website’s responsibility to honour that preference. ([Here’s how Apple does it](https://webkit.org/blog/7551/responsive-design-for-motion/).)

I have ‘reduced motion’ toggled on my computer’s accessibility preferences. But those logos still animate.

Here's a [good article summarising everything about prefers-reduced-motion](https://css-tricks.com/revisiting-prefers-reduced-motion-the-reduced-motion-media-query/). But there really isn't much to it. My pseudo-code example above says it all.
